# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Server:
    runs-on: ubuntu-latest
    container:
      image: rootproject/root:latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      # start the server via root, it will close automatically, we just check there are no mistakes in the macro
      - name: ROOT macro check
        run: root GeometryBrowser.C

  Node:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./node

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install additional dependencies
        run: sudo apt-get install xserver-xorg-dev libxi-dev libxext-dev -y

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "15"
          check-latest: true

      - name: Install node_modules
        run: npm install

      - name: JSROOT read json.gz geometry
        run: node readJson.js
      # temporary removed due to error with gl in ubuntu (works on windows)
      #- name: JSROOT save SVG image of geometry
      #  run: node saveSVG.js
